const LEETCODE_DATABASE = [
  {
    category: "1. Array & String",
    patterns: ["Two Pointers", "Sliding Window", "Prefix Sums", "In-place Mutation"],
    problems: [
      { id: 88, title: "Merge Sorted Array", difficulty: "Easy", slug: "merge-sorted-array" },
      { id: 27, title: "Remove Element", difficulty: "Easy", slug: "remove-element" },
      { id: 26, title: "Remove Duplicates from Sorted Array", difficulty: "Easy", slug: "remove-duplicates-from-sorted-array" },
      { id: 80, title: "Remove Duplicates from Sorted Array II", difficulty: "Medium", slug: "remove-duplicates-from-sorted-array-ii" },
      { id: 169, title: "Majority Element", difficulty: "Easy", slug: "majority-element" },
      { id: 189, title: "Rotate Array", difficulty: "Medium", slug: "rotate-array" },
      { id: 121, title: "Best Time to Buy and Sell Stock", difficulty: "Easy", slug: "best-time-to-buy-and-sell-stock" },
      { id: 122, title: "Best Time to Buy and Sell Stock II", difficulty: "Medium", slug: "best-time-to-buy-and-sell-stock-ii" },
      { id: 55, title: "Jump Game", difficulty: "Medium", slug: "jump-game" },
      { id: 45, title: "Jump Game II", difficulty: "Medium", slug: "jump-game-ii" },
      { id: 274, title: "H-Index", difficulty: "Medium", slug: "h-index" },
      { id: 380, title: "Insert Delete GetRandom O(1)", difficulty: "Medium", slug: "insert-delete-getrandom-o1" },
      { id: 238, title: "Product of Array Except Self", difficulty: "Medium", slug: "product-of-array-except-self" },
      { id: 134, title: "Gas Station", difficulty: "Medium", slug: "gas-station" },
      { id: 135, title: "Candy", difficulty: "Hard", slug: "candy" },
      { id: 42, title: "Trapping Rain Water", difficulty: "Hard", slug: "trapping-rain-water" },
      { id: 13, title: "Roman to Integer", difficulty: "Easy", slug: "roman-to-integer" },
      { id: 12, title: "Integer to Roman", difficulty: "Medium", slug: "integer-to-roman" },
      { id: 58, title: "Length of Last Word", difficulty: "Easy", slug: "length-of-last-word" },
      { id: 14, title: "Longest Common Prefix", difficulty: "Easy", slug: "longest-common-prefix" },
      { id: 151, title: "Reverse Words in a String", difficulty: "Medium", slug: "reverse-words-in-a-string" },
      { id: 6, title: "Zigzag Conversion", difficulty: "Medium", slug: "zigzag-conversion" },
      { id: 28, title: "Find the Index of the First Occurrence in a String", difficulty: "Easy", slug: "find-the-index-of-the-first-occurrence-in-a-string" },
      { id: 68, title: "Text Justification", difficulty: "Hard", slug: "text-justification" },
      { id: 1, title: "Two Sum", difficulty: "Easy", slug: "two-sum" },
      { id: 31, title: "Next Permutation", difficulty: "Medium", slug: "next-permutation" },
      { id: 48, title: "Rotate Image", difficulty: "Medium", slug: "rotate-image" },
      { id: 53, title: "Maximum Subarray", difficulty: "Medium", slug: "maximum-subarray" },
      { id: 56, title: "Merge Intervals", difficulty: "Medium", slug: "merge-intervals" },
      { id: 73, title: "Set Matrix Zeroes", difficulty: "Medium", slug: "set-matrix-zeroes" },
      { id: 118, title: "Pascal's Triangle", difficulty: "Easy", slug: "pascals-triangle" },
      { id: 283, title: "Move Zeroes", difficulty: "Easy", slug: "move-zeroes" },
      { id: 347, title: "Top K Frequent Elements", difficulty: "Medium", slug: "top-k-frequent-elements" },
      { id: 448, title: "Find All Numbers Disappeared in an Array", difficulty: "Easy", slug: "find-all-numbers-disappeared-in-an-array" },
      { id: 560, title: "Subarray Sum Equals K", difficulty: "Medium", slug: "subarray-sum-equals-k" },
      { id: 239, title: "Sliding Window Maximum", difficulty: "Hard", slug: "sliding-window-maximum" },
      { id: 41, title: "First Missing Positive", difficulty: "Hard", slug: "first-missing-positive" },
      { id: 287, title: "Find the Duplicate Number", difficulty: "Medium", slug: "find-the-duplicate-number" },
      { id: 316, title: "Remove Duplicate Letters", difficulty: "Medium", slug: "remove-duplicate-letters" },
      { id: 1071, title: "Greatest Common Divisor of Strings", difficulty: "Easy", slug: "greatest-common-divisor-of-strings" }
    ]
  },
  {
    category: "2. Two Pointers & Sliding Window",
    patterns: ["Opposite-direction pointers", "Fast/Slow pointers", "Variable/Fixed-size windows"],
    problems: [
      { id: 125, title: "Valid Palindrome", difficulty: "Easy", slug: "valid-palindrome" },
      { id: 392, title: "Is Subsequence", difficulty: "Easy", slug: "is-subsequence" },
      { id: 167, title: "Two Sum II - Input Array Is Sorted", difficulty: "Medium", slug: "two-sum-ii-input-array-is-sorted" },
      { id: 11, title: "Container With Most Water", difficulty: "Medium", slug: "container-with-most-water" },
      { id: 15, title: "3Sum", difficulty: "Medium", slug: "3sum" },
      { id: 16, title: "3Sum Closest", difficulty: "Medium", slug: "3sum-closest" },
      { id: 18, title: "4Sum", difficulty: "Medium", slug: "4sum" },
      { id: 209, title: "Minimum Size Subarray Sum", difficulty: "Medium", slug: "minimum-size-subarray-sum" },
      { id: 3, title: "Longest Substring Without Repeating Characters", difficulty: "Medium", slug: "longest-substring-without-repeating-characters" },
      { id: 30, title: "Substring with Concatenation of All Words", difficulty: "Hard", slug: "substring-with-concatenation-of-all-words" },
      { id: 76, title: "Minimum Window Substring", difficulty: "Hard", slug: "minimum-window-substring" },
      { id: 340, title: "Longest Substring with At Most K Distinct Characters", difficulty: "Medium", slug: "longest-substring-with-at-most-k-distinct-characters" },
      { id: 424, title: "Longest Repeating Character Replacement", difficulty: "Medium", slug: "longest-repeating-character-replacement" },
      { id: 567, title: "Permutation in String", difficulty: "Medium", slug: "permutation-in-string" },
      { id: 1004, title: "Max Consecutive Ones III", difficulty: "Medium", slug: "max-consecutive-ones-iii" },
      { id: 992, title: "Subarrays with K Different Integers", difficulty: "Hard", slug: "subarrays-with-k-different-integers" },
      { id: 1456, title: "Maximum Number of Vowels in a Substring of Given Length", difficulty: "Medium", slug: "maximum-number-of-vowels-in-a-substring-of-given-length" },
      { id: 1493, title: "Longest Subarray of 1's After Deleting One Element", difficulty: "Medium", slug: "longest-subarray-of-1s-after-deleting-one-element" },
      { id: 977, title: "Squares of a Sorted Array", difficulty: "Easy", slug: "squares-of-a-sorted-array" },
      { id: 844, title: "Backspace String Compare", difficulty: "Easy", slug: "backspace-string-compare" },
      { id: 1100, title: "Find K-Length Substrings With No Repeated Characters", difficulty: "Medium", slug: "find-k-length-substrings-with-no-repeated-characters" },
      { id: 344, title: "Reverse String", difficulty: "Easy", slug: "reverse-string" },
      { id: 345, title: "Reverse Vowels of a String", difficulty: "Easy", slug: "reverse-vowels-of-a-string" },
      { id: 643, title: "Maximum Average Subarray I", difficulty: "Easy", slug: "maximum-average-subarray-i" },
      { id: 713, title: "Subarray Product Less Than K", difficulty: "Medium", slug: "subarray-product-less-than-k" },
      { id: 904, title: "Fruit Into Baskets", difficulty: "Medium", slug: "fruit-into-baskets" },
      { id: 986, title: "Interval List Intersections", difficulty: "Medium", slug: "interval-list-intersections" },
      { id: 1052, title: "Grumpy Bookstore Owner", difficulty: "Medium", slug: "grumpy-bookstore-owner" },
      { id: 1208, title: "Get Equal Substrings Within Budget", difficulty: "Medium", slug: "get-equal-substrings-within-budget" },
      { id: 1248, title: "Count Number of Nice Subarrays", difficulty: "Medium", slug: "count-number-of-nice-subarrays" },
      { id: 1358, title: "Number of Substrings Containing All Three Characters", difficulty: "Medium", slug: "number-of-substrings-containing-all-three-characters" },
      { id: 1423, title: "Maximum Points You Can Obtain from Cards", difficulty: "Medium", slug: "maximum-points-you-can-obtain-from-cards" },
      { id: 1658, title: "Minimum Operations to Reduce X to Zero", difficulty: "Medium", slug: "minimum-operations-to-reduce-x-to-zero" },
      { id: 1838, title: "Frequency of the Most Frequent Element", difficulty: "Medium", slug: "frequency-of-the-most-frequent-element" },
      { id: 1871, title: "Jump Game VII", difficulty: "Medium", slug: "jump-game-vii" }
    ]
  },
  {
    category: "3. Matrix & Grid",
    patterns: ["2D Traversals", "Direction vectors", "In-place marking"],
    problems: [
      { id: 36, title: "Valid Sudoku", difficulty: "Medium", slug: "valid-sudoku" },
      { id: 54, title: "Spiral Matrix", difficulty: "Medium", slug: "spiral-matrix" },
      { id: 48, title: "Rotate Image", difficulty: "Medium", slug: "rotate-image" },
      { id: 73, title: "Set Matrix Zeroes", difficulty: "Medium", slug: "set-matrix-zeroes" },
      { id: 289, title: "Game of Life", difficulty: "Medium", slug: "game-of-life" },
      { id: 74, title: "Search a 2D Matrix", difficulty: "Medium", slug: "search-a-2d-matrix" },
      { id: 240, title: "Search a 2D Matrix II", difficulty: "Medium", slug: "search-a-2d-matrix-ii" },
      { id: 304, title: "Range Sum Query 2D - Immutable", difficulty: "Medium", slug: "range-sum-query-2d-immutable" },
      { id: 59, title: "Spiral Matrix II", difficulty: "Medium", slug: "spiral-matrix-ii" },
      { id: 867, title: "Transpose Matrix", difficulty: "Easy", slug: "transpose-matrix" },
      { id: 1329, title: "Sort the Matrix Diagonally", difficulty: "Medium", slug: "sort-the-matrix-diagonally" },
      { id: 1351, title: "Count Negative Numbers in a Sorted Matrix", difficulty: "Easy", slug: "count-negative-numbers-in-a-sorted-matrix" },
      { id: 1424, title: "Diagonal Traverse II", difficulty: "Medium", slug: "diagonal-traverse-ii" },
      { id: 1572, title: "Matrix Diagonal Sum", difficulty: "Easy", slug: "matrix-diagonal-sum" },
      { id: 1605, title: "Find Valid Matrix Given Row and Column Sums", difficulty: "Medium", slug: "find-valid-matrix-given-row-and-column-sums" },
      { id: 63, title: "Unique Paths II", difficulty: "Medium", slug: "unique-paths-ii" },
      { id: 64, title: "Minimum Path Sum", difficulty: "Medium", slug: "minimum-path-sum" },
      { id: 221, title: "Maximal Square", difficulty: "Medium", slug: "maximal-square" },
      { id: 85, title: "Maximal Rectangle", difficulty: "Hard", slug: "maximal-rectangle" },
      { id: 1091, title: "Shortest Path in Binary Matrix", difficulty: "Medium", slug: "shortest-path-in-binary-matrix" },
      { id: 130, title: "Surrounded Regions", difficulty: "Medium", slug: "surrounded-regions" },
      { id: 200, title: "Number of Islands", difficulty: "Medium", slug: "number-of-islands" },
      { id: 695, title: "Max Area of Island", difficulty: "Medium", slug: "max-area-of-island" },
      { id: 994, title: "Rotting Oranges", difficulty: "Medium", slug: "rotting-oranges" },
      { id: 1254, title: "Number of Closed Islands", difficulty: "Medium", slug: "number-of-closed-islands" }
    ]
  },
  {
    category: "4. Hashmap & Hashset",
    patterns: ["Frequency counting", "Bucketing", "Complement lookup"],
    problems: [
      { id: 383, title: "Ransom Note", difficulty: "Easy", slug: "ransom-note" },
      { id: 205, title: "Isomorphic Strings", difficulty: "Easy", slug: "isomorphic-strings" },
      { id: 290, title: "Word Pattern", difficulty: "Easy", slug: "word-pattern" },
      { id: 242, title: "Valid Anagram", difficulty: "Easy", slug: "valid-anagram" },
      { id: 49, title: "Group Anagrams", difficulty: "Medium", slug: "group-anagrams" },
      { id: 1, title: "Two Sum", difficulty: "Easy", slug: "two-sum" },
      { id: 202, title: "Happy Number", difficulty: "Easy", slug: "happy-number" },
      { id: 219, title: "Contains Duplicate II", difficulty: "Easy", slug: "contains-duplicate-ii" },
      { id: 128, title: "Longest Consecutive Sequence", difficulty: "Medium", slug: "longest-consecutive-sequence" },
      { id: 217, title: "Contains Duplicate", difficulty: "Easy", slug: "contains-duplicate" },
      { id: 349, title: "Intersection of Two Arrays", difficulty: "Easy", slug: "intersection-of-two-arrays" },
      { id: 350, title: "Intersection of Two Arrays II", difficulty: "Easy", slug: "intersection-of-two-arrays-ii" },
      { id: 387, title: "First Unique Character in a String", difficulty: "Easy", slug: "first-unique-character-in-a-string" },
      { id: 454, title: "4Sum II", difficulty: "Medium", slug: "4sum-ii" },
      { id: 535, title: "Encode and Decode TinyURL", difficulty: "Medium", slug: "encode-and-decode-tinyurl" },
      { id: 554, title: "Brick Wall", difficulty: "Medium", slug: "brick-wall" },
      { id: 599, title: "Minimum Index Sum of Two Lists", difficulty: "Easy", slug: "minimum-index-sum-of-two-lists" },
      { id: 705, title: "Design HashSet", difficulty: "Easy", slug: "design-hashset" },
      { id: 706, title: "Design HashMap", difficulty: "Easy", slug: "design-hashmap" },
      { id: 771, title: "Jewels and Stones", difficulty: "Easy", slug: "jewels-and-stones" },
      { id: 811, title: "Subdomain Visit Count", difficulty: "Medium", slug: "subdomain-visit-count" },
      { id: 953, title: "Verifying an Alien Dictionary", difficulty: "Easy", slug: "verifying-an-alien-dictionary" },
      { id: 1152, title: "Analyze User Website Visit Pattern", difficulty: "Medium", slug: "analyze-user-website-visit-pattern" },
      { id: 1429, title: "First Unique Number", difficulty: "Medium", slug: "first-unique-number" },
      { id: 1657, title: "Determine if Two Strings Are Close", difficulty: "Medium", slug: "determine-if-two-strings-are-close" }
    ]
  },
  {
    category: "5. Intervals",
    patterns: ["Sorting by start time", "Overlap conditions", "Sweep line"],
    problems: [
      { id: 228, title: "Summary Ranges", difficulty: "Easy", slug: "summary-ranges" },
      { id: 56, title: "Merge Intervals", difficulty: "Medium", slug: "merge-intervals" },
      { id: 57, title: "Insert Interval", difficulty: "Medium", slug: "insert-interval" },
      { id: 452, title: "Minimum Number of Arrows to Burst Balloons", difficulty: "Medium", slug: "minimum-number-of-arrows-to-burst-balloons" },
      { id: 252, title: "Meeting Rooms", difficulty: "Easy", slug: "meeting-rooms" },
      { id: 253, title: "Meeting Rooms II", difficulty: "Medium", slug: "meeting-rooms-ii" },
      { id: 435, title: "Non-overlapping Intervals", difficulty: "Medium", slug: "non-overlapping-intervals" },
      { id: 1288, title: "Remove Covered Intervals", difficulty: "Medium", slug: "remove-covered-intervals" },
      { id: 759, title: "Employee Free Time", difficulty: "Hard", slug: "employee-free-time" },
      { id: 1024, title: "Video Stitching", difficulty: "Medium", slug: "video-stitching" },
      { id: 1272, title: "Remove Interval", difficulty: "Medium", slug: "remove-interval" },
      { id: 986, title: "Interval List Intersections", difficulty: "Medium", slug: "interval-list-intersections" },
      { id: 732, title: "My Calendar III", difficulty: "Hard", slug: "my-calendar-iii" },
      { id: 729, title: "My Calendar I", difficulty: "Medium", slug: "my-calendar-i" },
      { id: 731, title: "My Calendar II", difficulty: "Medium", slug: "my-calendar-ii" },
      { id: 1851, title: "Minimum Interval to Include Each Query", difficulty: "Hard", slug: "minimum-interval-to-include-each-query" },
      { id: 218, title: "The Skyline Problem", difficulty: "Hard", slug: "the-skyline-problem" },
      { id: 352, title: "Data Stream as Disjoint Intervals", difficulty: "Hard", slug: "data-stream-as-disjoint-intervals" },
      { id: 1094, title: "Car Pooling", difficulty: "Medium", slug: "car-pooling" },
      { id: 1109, title: "Corporate Flight Bookings", difficulty: "Medium", slug: "corporate-flight-bookings" }
    ]
  },
  {
    category: "6. Stack & Monotonic Stack",
    patterns: ["Parentheses matching", "Next Greater Element", "Histogram processing"],
    problems: [
      { id: 20, title: "Valid Parentheses", difficulty: "Easy", slug: "valid-parentheses" },
      { id: 71, title: "Simplify Path", difficulty: "Medium", slug: "simplify-path" },
      { id: 155, title: "Min Stack", difficulty: "Medium", slug: "min-stack" },
      { id: 150, title: "Evaluate Reverse Polish Notation", difficulty: "Medium", slug: "evaluate-reverse-polish-notation" },
      { id: 224, title: "Basic Calculator", difficulty: "Hard", slug: "basic-calculator" },
      { id: 227, title: "Basic Calculator II", difficulty: "Medium", slug: "basic-calculator-ii" },
      { id: 772, title: "Basic Calculator III", difficulty: "Hard", slug: "basic-calculator-iii" },
      { id: 84, title: "Largest Rectangle in Histogram", difficulty: "Hard", slug: "largest-rectangle-in-histogram" },
      { id: 739, title: "Daily Temperatures", difficulty: "Medium", slug: "daily-temperatures" },
      { id: 496, title: "Next Greater Element I", difficulty: "Easy", slug: "next-greater-element-i" },
      { id: 503, title: "Next Greater Element II", difficulty: "Medium", slug: "next-greater-element-ii" },
      { id: 402, title: "Remove K Digits", difficulty: "Medium", slug: "remove-k-digits" },
      { id: 316, title: "Remove Duplicate Letters", difficulty: "Medium", slug: "remove-duplicate-letters" },
      { id: 901, title: "Online Stock Span", difficulty: "Medium", slug: "online-stock-span" },
      { id: 853, title: "Car Fleet", difficulty: "Medium", slug: "car-fleet" },
      { id: 1776, title: "Car Fleet II", difficulty: "Hard", slug: "car-fleet-ii" },
      { id: 394, title: "Decode String", difficulty: "Medium", slug: "decode-string" },
      { id: 946, title: "Validate Stack Sequences", difficulty: "Medium", slug: "validate-stack-sequences" },
      { id: 1019, title: "Next Greater Node In Linked List", difficulty: "Medium", slug: "next-greater-node-in-linked-list" },
      { id: 1047, title: "Remove All Adjacent Duplicates In String", difficulty: "Easy", slug: "remove-all-adjacent-duplicates-in-string" },
      { id: 1209, title: "Remove All Adjacent Duplicates in String II", difficulty: "Medium", slug: "remove-all-adjacent-duplicates-in-string-ii" },
      { id: 1541, title: "Minimum Insertions to Balance a Parentheses String", difficulty: "Medium", slug: "minimum-insertions-to-balance-a-parentheses-string" },
      { id: 1944, title: "Number of Visible People in a Queue", difficulty: "Hard", slug: "number-of-visible-people-in-a-queue" },
      { id: 907, title: "Sum of Subarray Minimums", difficulty: "Medium", slug: "sum-of-subarray-minimums" },
      { id: 2104, title: "Sum of Subarray Ranges", difficulty: "Medium", slug: "sum-of-subarray-ranges" },
      { id: 2289, title: "Steps to Make Array Non-decreasing", difficulty: "Medium", slug: "steps-to-make-array-non-decreasing" },
      { id: 2334, title: "Subarray With Elements Greater Than Than Threshold", difficulty: "Hard", slug: "subarray-with-elements-greater-than-threshold" },
      { id: 32, title: "Longest Valid Parentheses", difficulty: "Hard", slug: "longest-valid-parentheses" },
      { id: 636, title: "Exclusive Time of Functions", difficulty: "Medium", slug: "exclusive-time-of-functions" },
      { id: 856, title: "Score of Parentheses", difficulty: "Medium", slug: "score-of-parentheses" }
    ]
  },
  {
    category: "7. Linked List",
    patterns: ["Fast & Slow pointers", "In-place Reversal", "Sentinel nodes", "Merging"],
    problems: [
      { id: 141, title: "Linked List Cycle", difficulty: "Easy", slug: "linked-list-cycle" },
      { id: 142, title: "Linked List Cycle II", difficulty: "Medium", slug: "linked-list-cycle-ii" },
      { id: 2, title: "Add Two Numbers", difficulty: "Medium", slug: "add-two-numbers" },
      { id: 21, title: "Merge Two Sorted Lists", difficulty: "Easy", slug: "merge-two-sorted-lists" },
      { id: 138, title: "Copy List with Random Pointer", difficulty: "Medium", slug: "copy-list-with-random-pointer" },
      { id: 92, title: "Reverse Linked List II", difficulty: "Medium", slug: "reverse-linked-list-ii" },
      { id: 25, title: "Reverse Nodes in k-Group", difficulty: "Hard", slug: "reverse-nodes-in-k-group" },
      { id: 19, title: "Remove Nth Node From End of List", difficulty: "Medium", slug: "remove-nth-node-from-end-of-list" },
      { id: 83, title: "Remove Duplicates from Sorted List", difficulty: "Easy", slug: "remove-duplicates-from-sorted-list" },
      { id: 82, title: "Remove Duplicates from Sorted List II", difficulty: "Medium", slug: "remove-duplicates-from-sorted-list-ii" },
      { id: 61, title: "Rotate List", difficulty: "Medium", slug: "rotate-list" },
      { id: 86, title: "Partition List", difficulty: "Medium", slug: "partition-list" },
      { id: 146, title: "LRU Cache", difficulty: "Medium", slug: "lru-cache" },
      { id: 460, title: "LFU Cache", difficulty: "Hard", slug: "lfu-cache" },
      { id: 206, title: "Reverse Linked List", difficulty: "Easy", slug: "reverse-linked-list" },
      { id: 234, title: "Palindrome Linked List", difficulty: "Easy", slug: "palindrome-linked-list" },
      { id: 143, title: "Reorder List", difficulty: "Medium", slug: "reorder-list" },
      { id: 148, title: "Sort List", difficulty: "Medium", slug: "sort-list" },
      { id: 23, title: "Merge k Sorted Lists", difficulty: "Hard", slug: "merge-k-sorted-lists" },
      { id: 160, title: "Intersection of Two Linked Lists", difficulty: "Easy", slug: "intersection-of-two-linked-lists" },
      { id: 328, title: "Odd Even Linked List", difficulty: "Medium", slug: "odd-even-linked-list" },
      { id: 445, title: "Add Two Numbers II", difficulty: "Medium", slug: "add-two-numbers-ii" },
      { id: 725, title: "Split Linked List in Parts", difficulty: "Medium", slug: "split-linked-list-in-parts" },
      { id: 876, title: "Middle of the Linked List", difficulty: "Easy", slug: "middle-of-the-linked-list" },
      { id: 1019, title: "Next Greater Node In Linked List", difficulty: "Medium", slug: "next-greater-node-in-linked-list" },
      { id: 1171, title: "Remove Zero Sum Consecutive Nodes from Linked List", difficulty: "Medium", slug: "remove-zero-sum-consecutive-nodes-from-linked-list" },
      { id: 1669, title: "Merge In Between Linked Lists", difficulty: "Medium", slug: "merge-in-between-linked-lists" },
      { id: 2058, title: "Find Min and Max Number of Nodes Between Critical Points", difficulty: "Medium", slug: "find-min-and-max-number-of-nodes-between-critical-points" },
      { id: 2130, title: "Maximum Twin Sum of a Linked List", difficulty: "Medium", slug: "maximum-twin-sum-of-a-linked-list" },
      { id: 2181, title: "Merge Nodes in Between Zeros", difficulty: "Medium", slug: "merge-nodes-in-between-zeros" }
    ]
  },
  {
    category: "8. Binary Tree - General & DFS",
    patterns: ["Recursion", "Pre/In/Post order Traversals", "Top-down vs Bottom-up"],
    problems: [
      { id: 104, title: "Maximum Depth of Binary Tree", difficulty: "Easy", slug: "maximum-depth-of-binary-tree" },
      { id: 100, title: "Same Tree", difficulty: "Easy", slug: "same-tree" },
      { id: 226, title: "Invert Binary Tree", difficulty: "Easy", slug: "invert-binary-tree" },
      { id: 101, title: "Symmetric Tree", difficulty: "Easy", slug: "symmetric-tree" },
      { id: 105, title: "Construct Binary Tree from Preorder and Inorder Traversal", difficulty: "Medium", slug: "construct-binary-tree-from-preorder-and-inorder-traversal" },
      { id: 106, title: "Construct Binary Tree from Inorder and Postorder Traversal", difficulty: "Medium", slug: "construct-binary-tree-from-inorder-and-postorder-traversal" },
      { id: 117, title: "Populating Next Right Pointers in Each Node II", difficulty: "Medium", slug: "populating-next-right-pointers-in-each-node-ii" },
      { id: 114, title: "Flatten Binary Tree to Linked List", difficulty: "Medium", slug: "flatten-binary-tree-to-linked-list" },
      { id: 112, title: "Path Sum", difficulty: "Easy", slug: "path-sum" },
      { id: 113, title: "Path Sum II", difficulty: "Medium", slug: "path-sum-ii" },
      { id: 437, title: "Path Sum III", difficulty: "Medium", slug: "path-sum-iii" },
      { id: 129, title: "Sum Root to Leaf Numbers", difficulty: "Medium", slug: "sum-root-to-leaf-numbers" },
      { id: 124, title: "Binary Tree Maximum Path Sum", difficulty: "Hard", slug: "binary-tree-maximum-path-sum" },
      { id: 173, title: "Binary Search Tree Iterator", difficulty: "Medium", slug: "binary-search-tree-iterator" },
      { id: 222, title: "Count Complete Tree Nodes", difficulty: "Easy", slug: "count-complete-tree-nodes" },
      { id: 236, title: "Lowest Common Ancestor of a Binary Tree", difficulty: "Medium", slug: "lowest-common-ancestor-of-a-binary-tree" },
      { id: 110, title: "Balanced Binary Tree", difficulty: "Easy", slug: "balanced-binary-tree" },
      { id: 111, title: "Minimum Depth of Binary Tree", difficulty: "Easy", slug: "minimum-depth-of-binary-tree" },
      { id: 144, title: "Binary Tree Preorder Traversal", difficulty: "Easy", slug: "binary-tree-preorder-traversal" },
      { id: 94, title: "Binary Tree Inorder Traversal", difficulty: "Easy", slug: "binary-tree-inorder-traversal" },
      { id: 145, title: "Binary Tree Postorder Traversal", difficulty: "Easy", slug: "binary-tree-postorder-traversal" },
      { id: 257, title: "Binary Tree Paths", difficulty: "Easy", slug: "binary-tree-paths" },
      { id: 297, title: "Serialize and Deserialize Binary Tree", difficulty: "Hard", slug: "serialize-and-deserialize-binary-tree" },
      { id: 337, title: "House Robber III", difficulty: "Medium", slug: "house-robber-iii" },
      { id: 543, title: "Diameter of Binary Tree", difficulty: "Easy", slug: "diameter-of-binary-tree" },
      { id: 572, title: "Subtree of Another Tree", difficulty: "Easy", slug: "subtree-of-another-tree" },
      { id: 617, title: "Merge Two Binary Trees", difficulty: "Easy", slug: "merge-two-binary-trees" },
      { id: 652, title: "Find Duplicate Subtrees", difficulty: "Medium", slug: "find-duplicate-subtrees" },
      { id: 663, title: "Equal Tree Partition", difficulty: "Medium", slug: "equal-tree-partition" },
      { id: 863, title: "All Nodes Distance K in Binary Tree", difficulty: "Medium", slug: "all-nodes-distance-k-in-binary-tree" },
      { id: 889, title: "Construct Binary Tree from Preorder and Postorder Traversal", difficulty: "Medium", slug: "construct-binary-tree-from-preorder-and-postorder-traversal" },
      { id: 968, title: "Binary Tree Cameras", difficulty: "Hard", slug: "binary-tree-cameras" },
      { id: 987, title: "Vertical Order Traversal of a Binary Tree", difficulty: "Hard", slug: "vertical-order-traversal-of-a-binary-tree" },
      { id: 1026, title: "Maximum Difference Between Node and Ancestor", difficulty: "Medium", slug: "maximum-difference-between-node-and-ancestor" },
      { id: 1372, title: "Longest ZigZag Path in a Binary Tree", difficulty: "Medium", slug: "longest-zigzag-path-in-a-binary-tree" }
    ]
  },
  {
    category: "9. Binary Tree - BFS & Level Order",
    patterns: ["Queue-based level processing", "Zigzag bounds", "Tree view techniques"],
    problems: [
      { id: 199, title: "Binary Tree Right Side View", difficulty: "Medium", slug: "binary-tree-right-side-view" },
      { id: 637, title: "Average of Levels in Binary Tree", difficulty: "Easy", slug: "average-of-levels-in-binary-tree" },
      { id: 102, title: "Binary Tree Level Order Traversal", difficulty: "Medium", slug: "binary-tree-level-order-traversal" },
      { id: 103, title: "Binary Tree Zigzag Level Order Traversal", difficulty: "Medium", slug: "binary-tree-zigzag-level-order-traversal" },
      { id: 107, title: "Binary Tree Level Order Traversal II", difficulty: "Medium", slug: "binary-tree-level-order-traversal-ii" },
      { id: 111, title: "Minimum Depth of Binary Tree", difficulty: "Easy", slug: "minimum-depth-of-binary-tree" },
      { id: 116, title: "Populating Next Right Pointers in Each Node", difficulty: "Medium", slug: "populating-next-right-pointers-in-each-node" },
      { id: 314, title: "Binary Tree Vertical Order Traversal", difficulty: "Medium", slug: "binary-tree-vertical-order-traversal" },
      { id: 513, title: "Find Bottom Left Tree Value", difficulty: "Medium", slug: "find-bottom-left-tree-value" },
      { id: 515, title: "Find Largest Value in Each Tree Row", difficulty: "Medium", slug: "find-largest-value-in-each-tree-row" },
      { id: 662, title: "Maximum Width of Binary Tree", difficulty: "Medium", slug: "maximum-width-of-binary-tree" },
      { id: 958, title: "Check Completeness of a Binary Tree", difficulty: "Medium", slug: "check-completeness-of-a-binary-tree" },
      { id: 1161, title: "Maximum Level Sum of a Binary Tree", difficulty: "Medium", slug: "maximum-level-sum-of-a-binary-tree" },
      { id: 1302, title: "Deepest Leaves Sum", difficulty: "Medium", slug: "deepest-leaves-sum" },
      { id: 1602, title: "Find Nearest Right Node in Binary Tree", difficulty: "Medium", slug: "find-nearest-right-node-in-binary-tree" },
      { id: 2415, title: "Reverse Odd Levels of Binary Tree", difficulty: "Medium", slug: "reverse-odd-levels-of-binary-tree" },
      { id: 2471, title: "Minimum Number of Operations to Sort a Binary Tree by Level", difficulty: "Medium", slug: "minimum-number-of-operations-to-sort-a-binary-tree-by-level" },
      { id: 2641, title: "Cousins in Binary Tree II", difficulty: "Medium", slug: "cousins-in-binary-tree-ii" },
      { id: 429, title: "N-ary Tree Level Order Traversal", difficulty: "Medium", slug: "n-ary-tree-level-order-traversal" },
      { id: 993, title: "Cousins in Binary Tree", difficulty: "Easy", slug: "cousins-in-binary-tree" }
    ]
  },
  {
    category: "10. Binary Search Tree (BST)",
    patterns: ["Inorder traversal invariants", "Divide & Conquer search space"],
    problems: [
      { id: 530, title: "Minimum Absolute Difference in BST", difficulty: "Easy", slug: "minimum-absolute-difference-in-bst" },
      { id: 230, title: "Kth Smallest Element in a BST", difficulty: "Medium", slug: "kth-smallest-element-in-a-bst" },
      { id: 98, title: "Validate Binary Search Tree", difficulty: "Medium", slug: "validate-binary-search-tree" },
      { id: 235, title: "Lowest Common Ancestor of a Binary Search Tree", difficulty: "Medium", slug: "lowest-common-ancestor-of-a-binary-search-tree" },
      { id: 700, title: "Search in a Binary Search Tree", difficulty: "Easy", slug: "search-in-a-binary-search-tree" },
      { id: 701, title: "Insert into a Binary Search Tree", difficulty: "Medium", slug: "insert-into-a-binary-search-tree" },
      { id: 450, title: "Delete Node in a BST", difficulty: "Medium", slug: "delete-node-in-a-bst" },
      { id: 108, title: "Convert Sorted Array to Binary Search Tree", difficulty: "Easy", slug: "convert-sorted-array-to-binary-search-tree" },
      { id: 109, title: "Convert Sorted List to Binary Search Tree", difficulty: "Medium", slug: "convert-sorted-list-to-binary-search-tree" },
      { id: 99, title: "Recover Binary Search Tree", difficulty: "Medium", slug: "recover-binary-search-tree" },
      { id: 270, title: "Closest Binary Search Tree Value", difficulty: "Easy", slug: "closest-binary-search-tree-value" },
      { id: 501, title: "Find Mode in Binary Search Tree", difficulty: "Easy", slug: "find-mode-in-binary-search-tree" },
      { id: 669, title: "Trim a Binary Search Tree", difficulty: "Medium", slug: "trim-a-binary-search-tree" },
      { id: 1382, title: "Balance a Binary Search Tree", difficulty: "Medium", slug: "balance-a-binary-search-tree" },
      { id: 1008, title: "Construct Binary Search Tree from Preorder Traversal", difficulty: "Medium", slug: "construct-binary-search-tree-from-preorder-traversal" }
    ]
  },
  {
    category: "11. Graph - General, DFS & BFS",
    patterns: ["Cycle detection", "Connected components", "Topological Sort", "Bipartite checks"],
    problems: [
      { id: 200, title: "Number of Islands", difficulty: "Medium", slug: "number-of-islands" },
      { id: 130, title: "Surrounded Regions", difficulty: "Medium", slug: "surrounded-regions" },
      { id: 133, title: "Clone Graph", difficulty: "Medium", slug: "clone-graph" },
      { id: 399, title: "Evaluate Division", difficulty: "Medium", slug: "evaluate-division" },
      { id: 207, title: "Course Schedule", difficulty: "Medium", slug: "course-schedule" },
      { id: 210, title: "Course Schedule II", difficulty: "Medium", slug: "course-schedule-ii" },
      { id: 261, title: "Graph Valid Tree", difficulty: "Medium", slug: "graph-valid-tree" },
      { id: 323, title: "Number of Connected Components in an Undirected Graph", difficulty: "Medium", slug: "number-of-connected-components-in-an-undirected-graph" },
      { id: 684, title: "Redundant Connection", difficulty: "Medium", slug: "redundant-connection" },
      { id: 685, title: "Redundant Connection II", difficulty: "Hard", slug: "redundant-connection-ii" },
      { id: 785, title: "Is Graph Bipartite?", difficulty: "Medium", slug: "is-graph-bipartite" },
      { id: 797, title: "All Paths From Source to Target", difficulty: "Medium", slug: "all-paths-from-source-to-target" },
      { id: 802, title: "Find Eventual Safe States", difficulty: "Medium", slug: "find-eventual-safe-states" },
      { id: 841, title: "Keys and Rooms", difficulty: "Medium", slug: "keys-and-rooms" },
      { id: 886, title: "Possible Bipartition", difficulty: "Medium", slug: "possible-bipartition" },
      { id: 990, title: "Satisfiability of Equality Equations", difficulty: "Medium", slug: "satisfiability-of-equality-equations" },
      { id: 1129, title: "Shortest Path with Alternating Colors", difficulty: "Medium", slug: "shortest-path-with-alternating-colors" },
      { id: 1162, title: "As Far from Land as Possible", difficulty: "Medium", slug: "as-far-from-land-as-possible" },
      { id: 1319, title: "Number of Operations to Make Network Connected", difficulty: "Medium", slug: "number-of-operations-to-make-network-connected" },
      { id: 1334, title: "Find the City With the Smallest Number of Neighbors", difficulty: "Medium", slug: "find-the-city-with-the-smallest-number-of-neighbors-at-a-threshold-distance" },
      { id: 1466, title: "Reorder Routes to Make All Paths Lead to the City Zero", difficulty: "Medium", slug: "reorder-routes-to-make-all-paths-lead-to-the-city-zero" },
      { id: 1557, title: "Minimum Number of Vertices to Reach All Nodes", difficulty: "Medium", slug: "minimum-number-of-vertices-to-reach-all-nodes" },
      { id: 1971, title: "Find if Path Exists in Graph", difficulty: "Easy", slug: "find-if-path-exists-in-graph" },
      { id: 2101, title: "Detonate the Maximum Bombs", difficulty: "Medium", slug: "detonate-the-maximum-bombs" },
      { id: 2360, title: "Longest Cycle in a Graph", difficulty: "Hard", slug: "longest-cycle-in-a-graph" },
      { id: 2492, title: "Minimum Score of a Path Between Two Cities", difficulty: "Medium", slug: "minimum-score-of-a-path-between-two-cities" },
      { id: 2608, title: "Shortest Cycle in a Graph", difficulty: "Hard", slug: "shortest-cycle-in-a-graph" },
      { id: 909, title: "Snakes and Ladders", difficulty: "Medium", slug: "snakes-and-ladders" },
      { id: 433, title: "Minimum Genetic Mutation", difficulty: "Medium", slug: "minimum-genetic-mutation" },
      { id: 127, title: "Word Ladder", difficulty: "Hard", slug: "word-ladder" },
      { id: 126, title: "Word Ladder II", difficulty: "Hard", slug: "word-ladder-ii" },
      { id: 743, title: "Network Delay Time", difficulty: "Medium", slug: "network-delay-time" },
      { id: 787, title: "Cheapest Flights Within K Stops", difficulty: "Medium", slug: "cheapest-flights-within-k-stops" },
      { id: 1631, title: "Path With Minimum Effort", difficulty: "Medium", slug: "path-with-minimum-effort" },
      { id: 778, title: "Swim in Rising Water", difficulty: "Hard", slug: "swim-in-rising-water" }
    ]
  },
  {
    category: "12. Trie & String Search",
    patterns: ["Prefix trees", "Backtracking with Tries", "Aho-Corasick basics"],
    problems: [
      { id: 208, title: "Implement Trie (Prefix Tree)", difficulty: "Medium", slug: "implement-trie-prefix-tree" },
      { id: 211, title: "Design Add and Search Words Data Structure", difficulty: "Medium", slug: "design-add-and-search-words-data-structure" },
      { id: 212, title: "Word Search II", difficulty: "Hard", slug: "word-search-ii" },
      { id: 336, title: "Palindrome Pairs", difficulty: "Hard", slug: "palindrome-pairs" },
      { id: 421, title: "Maximum XOR of Two Numbers in an Array", difficulty: "Medium", slug: "maximum-xor-of-two-numbers-in-an-array" },
      { id: 642, title: "Design Search Autocomplete System", difficulty: "Hard", slug: "design-search-autocomplete-system" },
      { id: 648, title: "Replace Words", difficulty: "Medium", slug: "replace-words" },
      { id: 677, title: "Map Sum Pairs", difficulty: "Medium", slug: "map-sum-pairs" },
      { id: 720, title: "Longest Word in Dictionary", difficulty: "Medium", slug: "longest-word-in-dictionary" },
      { id: 745, title: "Prefix and Suffix Search", difficulty: "Hard", slug: "prefix-and-suffix-search" },
      { id: 820, title: "Short Encoding of Words", difficulty: "Medium", slug: "short-encoding-of-words" },
      { id: 1032, title: "Stream of Characters", difficulty: "Hard", slug: "stream-of-characters" },
      { id: 1268, title: "Search Suggestions System", difficulty: "Medium", slug: "search-suggestions-system" },
      { id: 1707, title: "Maximum XOR With an Element From Array", difficulty: "Hard", slug: "maximum-xor-with-an-element-from-array" },
      { id: 1804, title: "Implement Trie II (Prefix Tree)", difficulty: "Medium", slug: "implement-trie-ii-prefix-tree" }
    ]
  },
  {
    category: "13. Backtracking",
    patterns: ["State exploration", "Pruning", "Combinations vs Permutations vs Subsets"],
    problems: [
      { id: 17, title: "Letter Combinations of a Phone Number", difficulty: "Medium", slug: "letter-combinations-of-a-phone-number" },
      { id: 77, title: "Combinations", difficulty: "Medium", slug: "combinations" },
      { id: 46, title: "Permutations", difficulty: "Medium", slug: "permutations" },
      { id: 47, title: "Permutations II", difficulty: "Medium", slug: "permutations-ii" },
      { id: 39, title: "Combination Sum", difficulty: "Medium", slug: "combination-sum" },
      { id: 40, title: "Combination Sum II", difficulty: "Medium", slug: "combination-sum-ii" },
      { id: 216, title: "Combination Sum III", difficulty: "Medium", slug: "combination-sum-iii" },
      { id: 377, title: "Combination Sum IV", difficulty: "Medium", slug: "combination-sum-iv" },
      { id: 52, title: "N-Queens II", difficulty: "Hard", slug: "n-queens-ii" },
      { id: 51, title: "N-Queens", difficulty: "Hard", slug: "n-queens" },
      { id: 22, title: "Generate Parentheses", difficulty: "Medium", slug: "generate-parentheses" },
      { id: 79, title: "Word Search", difficulty: "Medium", slug: "word-search" },
      { id: 78, title: "Subsets", difficulty: "Medium", slug: "subsets" },
      { id: 90, title: "Subsets II", difficulty: "Medium", slug: "subsets-ii" },
      { id: 131, title: "Palindrome Partitioning", difficulty: "Medium", slug: "palindrome-partitioning" },
      { id: 93, title: "Restore IP Addresses", difficulty: "Medium", slug: "restore-ip-addresses" },
      { id: 301, title: "Remove Invalid Parentheses", difficulty: "Hard", slug: "remove-invalid-parentheses" },
      { id: 37, title: "Sudoku Solver", difficulty: "Hard", slug: "sudoku-solver" },
      { id: 282, title: "Expression Add Operators", difficulty: "Hard", slug: "expression-add-operators" },
      { id: 473, title: "Matchsticks to Square", difficulty: "Medium", slug: "matchsticks-to-square" },
      { id: 698, title: "Partition to K Equal Subsets", difficulty: "Medium", slug: "partition-to-k-equal-subsets" },
      { id: 784, title: "Letter Case Permutation", difficulty: "Medium", slug: "letter-case-permutation" },
      { id: 842, title: "Split Array into Fibonacci Sequence", difficulty: "Medium", slug: "split-array-into-fibonacci-sequence" },
      { id: 980, title: "Unique Paths III", difficulty: "Hard", slug: "unique-paths-iii" },
      { id: 1219, title: "Path with Maximum Gold", difficulty: "Medium", slug: "path-with-maximum-gold" },
      { id: 1239, title: "Maximum Length of a Concatenated String with Unique Characters", difficulty: "Medium", slug: "maximum-length-of-a-concatenated-string-with-unique-characters" },
      { id: 1255, title: "Maximum Score Words Formed by Letters", difficulty: "Hard", slug: "maximum-score-words-formed-by-letters" },
      { id: 1718, title: "Construct the Lexicographically Largest Valid Sequence", difficulty: "Medium", slug: "construct-the-lexicographically-largest-valid-sequence" },
      { id: 1849, title: "Splitting a String Into Consecutive Values", difficulty: "Medium", slug: "splitting-a-string-into-consecutive-values" },
      { id: 1980, title: "Find Unique Binary String", difficulty: "Medium", slug: "find-unique-binary-string" }
    ]
  },
  {
    category: "14. Divide & Conquer & Binary Search",
    patterns: ["Binary searching on answer space", "Rotated array checks", "Range bounds"],
    problems: [
      { id: 108, title: "Convert Sorted Array to Binary Search Tree", difficulty: "Easy", slug: "convert-sorted-array-to-binary-search-tree" },
      { id: 148, title: "Sort List", difficulty: "Medium", slug: "sort-list" },
      { id: 427, title: "Construct Quad Tree", difficulty: "Medium", slug: "construct-quad-tree" },
      { id: 23, title: "Merge k Sorted Lists", difficulty: "Hard", slug: "merge-k-sorted-lists" },
      { id: 35, title: "Search Insert Position", difficulty: "Easy", slug: "search-insert-position" },
      { id: 74, title: "Search a 2D Matrix", difficulty: "Medium", slug: "search-a-2d-matrix" },
      { id: 162, title: "Find Peak Element", difficulty: "Medium", slug: "find-peak-element" },
      { id: 33, title: "Search in Rotated Sorted Array", difficulty: "Medium", slug: "search-in-rotated-sorted-array" },
      { id: 81, title: "Search in Rotated Sorted Array II", difficulty: "Medium", slug: "search-in-rotated-sorted-array-ii" },
      { id: 34, title: "Find First and Last Position of Element in Sorted Array", difficulty: "Medium", slug: "find-first-and-last-position-of-element-in-sorted-array" },
      { id: 153, title: "Find Minimum in Rotated Sorted Array", difficulty: "Medium", slug: "find-minimum-in-rotated-sorted-array" },
      { id: 154, title: "Find Minimum in Rotated Sorted Array II", difficulty: "Hard", slug: "find-minimum-in-rotated-sorted-array-ii" },
      { id: 4, title: "Median of Two Sorted Arrays", difficulty: "Hard", slug: "median-of-two-sorted-arrays" },
      { id: 69, title: "Sqrt(x)", difficulty: "Easy", slug: "sqrtx" },
      { id: 50, title: "Pow(x, n)", difficulty: "Medium", slug: "powx-n" },
      { id: 278, title: "First Bad Version", difficulty: "Easy", slug: "first-bad-version" },
      { id: 374, title: "Guess Number Higher or Lower", difficulty: "Easy", slug: "guess-number-higher-or-lower" },
      { id: 875, title: "Koko Eating Bananas", difficulty: "Medium", slug: "koko-eating-bananas" },
      { id: 1011, title: "Capacity To Ship Packages Within D Days", difficulty: "Medium", slug: "capacity-to-ship-packages-within-d-days" },
      { id: 1283, title: "Find the Smallest Divisor Given a Threshold", difficulty: "Medium", slug: "find-the-smallest-divisor-given-a-threshold" },
      { id: 1482, title: "Minimum Number of Days to Make m Bouquets", difficulty: "Medium", slug: "minimum-number-of-days-to-make-m-bouquets" },
      { id: 1539, title: "Kth Missing Positive Number", difficulty: "Easy", slug: "kth-missing-positive-number" },
      { id: 1628, title: "Design an Expression Tree With Evaluate Function", difficulty: "Medium", slug: "design-an-expression-tree-with-evaluate-function" },
      { id: 1802, title: "Maximum Value at a Given Index in a Bounded Array", difficulty: "Medium", slug: "maximum-value-at-a-given-index-in-a-bounded-array" },
      { id: 1870, title: "Minimum Speed to Arrive on Time", difficulty: "Medium", slug: "minimum-speed-to-arrive-on-time" },
      { id: 2064, title: "Minimized Maximum of Products Distributed to Any Store", difficulty: "Medium", slug: "minimized-maximum-of-products-distributed-to-any-store" },
      { id: 2226, title: "Maximum Candies Allocated to K Children", difficulty: "Medium", slug: "maximum-candies-allocated-to-k-children" },
      { id: 2300, title: "Successful Pairs of Spells and Potions", difficulty: "Medium", slug: "successful-pairs-of-spells-and-potions" },
      { id: 2401, title: "Longest Nice Subarray", difficulty: "Medium", slug: "longest-nice-subarray" },
      { id: 2439, title: "Minimize Maximum of Array", difficulty: "Medium", slug: "minimize-maximum-of-array" },
      { id: 2517, title: "Maximum Tastiness of Candy Basket", difficulty: "Medium", slug: "maximum-tastiness-of-candy-basket" },
      { id: 2560, title: "House Robber IV", difficulty: "Medium", slug: "house-robber-iv" },
      { id: 312, title: "Burst Balloons", difficulty: "Hard", slug: "burst-balloons" },
      { id: 493, title: "Reverse Pairs", difficulty: "Hard", slug: "reverse-pairs" },
      { id: 315, title: "Count of Smaller Numbers After Self", difficulty: "Hard", slug: "count-of-smaller-numbers-after-self" }
    ]
  },
  {
    category: "15. Heap / Priority Queue",
    patterns: ["Min-Heap/Max-Heap usage", "Top-K elements", "Median tracking", "K-way merges"],
    problems: [
      { id: 215, title: "Kth Largest Element in an Array", difficulty: "Medium", slug: "kth-largest-element-in-an-array" },
      { id: 502, title: "IPO", difficulty: "Hard", slug: "ipo" },
      { id: 373, title: "Find K Pairs with Smallest Sums", difficulty: "Medium", slug: "find-k-pairs-with-smallest-sums" },
      { id: 295, title: "Find Median from Data Stream", difficulty: "Hard", slug: "find-median-from-data-stream" },
      { id: 347, title: "Top K Frequent Elements", difficulty: "Medium", slug: "top-k-frequent-elements" },
      { id: 692, title: "Top K Frequent Words", difficulty: "Medium", slug: "top-k-frequent-words" },
      { id: 703, title: "Kth Largest Element in a Stream", difficulty: "Easy", slug: "kth-largest-element-in-a-stream" },
      { id: 973, title: "K Closest Points to Origin", difficulty: "Medium", slug: "k-closest-points-to-origin" },
      { id: 1046, title: "Last Stone Weight", difficulty: "Easy", slug: "last-stone-weight" },
      { id: 1834, title: "Single-Threaded CPU", difficulty: "Medium", slug: "single-threaded-cpu" },
      { id: 1882, title: "Process Tasks Using Servers", difficulty: "Medium", slug: "process-tasks-using-servers" },
      { id: 1942, title: "The Number of the Smallest Unoccupied Chair", difficulty: "Medium", slug: "the-number-of-the-smallest-unoccupied-chair" },
      { id: 2402, title: "Meeting Rooms III", difficulty: "Hard", slug: "meeting-rooms-iii" },
      { id: 2462, title: "Total Cost to Hire K Workers", difficulty: "Medium", slug: "total-cost-to-hire-k-workers" },
      { id: 2542, title: "Maximum Subsequence Score", difficulty: "Medium", slug: "maximum-subsequence-score" },
      { id: 621, title: "Task Scheduler", difficulty: "Medium", slug: "task-scheduler" },
      { id: 767, title: "Reorganize String", difficulty: "Medium", slug: "reorganize-string" },
      { id: 1405, title: "Longest Happy String", difficulty: "Medium", slug: "longest-happy-string" },
      { id: 1753, title: "Maximum Score From Removing Stones", difficulty: "Medium", slug: "maximum-score-from-removing-stones" },
      { id: 1792, title: "Maximum Average Pass Ratio", difficulty: "Medium", slug: "maximum-average-pass-ratio" }
    ]
  },
  {
    category: "16. Dynamic Programming - 1D, 2D & Advanced",
    patterns: ["Subproblem transitions", "Unbounded & 0/1 Knapsack", "LIS", "LCS", "Interval DP", "Bitmask DP"],
    problems: [
      { id: 70, title: "Climbing Stairs", difficulty: "Easy", slug: "climbing-stairs" },
      { id: 198, title: "House Robber", difficulty: "Medium", slug: "house-robber" },
      { id: 213, title: "House Robber II", difficulty: "Medium", slug: "house-robber-ii" },
      { id: 139, title: "Word Break", difficulty: "Medium", slug: "word-break" },
      { id: 140, title: "Word Break II", difficulty: "Hard", slug: "word-break-ii" },
      { id: 322, title: "Coin Change", difficulty: "Medium", slug: "coin-change" },
      { id: 518, title: "Coin Change II", difficulty: "Medium", slug: "coin-change-ii" },
      { id: 300, title: "Longest Increasing Subsequence", difficulty: "Medium", slug: "longest-increasing-subsequence" },
      { id: 120, title: "Triangle", difficulty: "Medium", slug: "triangle" },
      { id: 64, title: "Minimum Path Sum", difficulty: "Medium", slug: "minimum-path-sum" },
      { id: 62, title: "Unique Paths", difficulty: "Medium", slug: "unique-paths" },
      { id: 63, title: "Unique Paths II", difficulty: "Medium", slug: "unique-paths-ii" },
      { id: 5, title: "Longest Palindromic Substring", difficulty: "Medium", slug: "longest-palindromic-substring" },
      { id: 516, title: "Longest Palindromic Subsequence", difficulty: "Medium", slug: "longest-palindromic-subsequence" },
      { id: 97, title: "Interleaving String", difficulty: "Medium", slug: "interleaving-string" },
      { id: 72, title: "Edit Distance", difficulty: "Hard", slug: "edit-distance" },
      { id: 123, title: "Best Time to Buy and Sell Stock III", difficulty: "Hard", slug: "best-time-to-buy-and-sell-stock-iii" },
      { id: 188, title: "Best Time to Buy and Sell Stock IV", difficulty: "Hard", slug: "best-time-to-buy-and-sell-stock-iv" },
      { id: 309, title: "Best Time to Buy and Sell Stock with Cooldown", difficulty: "Medium", slug: "best-time-to-buy-and-sell-stock-with-cooldown" },
      { id: 714, title: "Best Time to Buy and Sell Stock with Transaction Fee", difficulty: "Medium", slug: "best-time-to-buy-and-sell-stock-with-transaction-fee" },
      { id: 1143, title: "Longest Common Subsequence", difficulty: "Medium", slug: "longest-common-subsequence" },
      { id: 1049, title: "Last Stone Weight II", difficulty: "Medium", slug: "last-stone-weight-ii" },
      { id: 416, title: "Partition Equal Subset Sum", difficulty: "Medium", slug: "partition-equal-subset-sum" },
      { id: 494, title: "Target Sum", difficulty: "Medium", slug: "target-sum" },
      { id: 10, title: "Regular Expression Matching", difficulty: "Hard", slug: "regular-expression-matching" },
      { id: 44, title: "Wildcard Matching", difficulty: "Hard", slug: "wildcard-matching" },
      { id: 329, title: "Longest Increasing Path in a Matrix", difficulty: "Hard", slug: "longest-increasing-path-in-a-matrix" },
      { id: 115, title: "Distinct Subsequences", difficulty: "Hard", slug: "distinct-subsequences" },
      { id: 91, title: "Decode Ways", difficulty: "Medium", slug: "decode-ways" },
      { id: 152, title: "Maximum Product Subarray", difficulty: "Medium", slug: "maximum-product-subarray" },
      { id: 279, title: "Perfect Squares", difficulty: "Medium", slug: "perfect-squares" },
      { id: 368, title: "Largest Divisible Subset", difficulty: "Medium", slug: "largest-divisible-subset" },
      { id: 474, title: "Ones and Zeroes", difficulty: "Medium", slug: "ones-and-zeroes" },
      { id: 583, title: "Delete Operation for Two Strings", difficulty: "Medium", slug: "delete-operation-for-two-strings" },
      { id: 647, title: "Palindromic Substrings", difficulty: "Medium", slug: "palindromic-substrings" },
      { id: 712, title: "Minimum ASCII Delete Sum for Two Strings", difficulty: "Medium", slug: "minimum-ascii-delete-sum-for-two-strings" },
      { id: 1092, title: "Shortest Common Supersequence", difficulty: "Hard", slug: "shortest-common-supersequence" },
      { id: 1130, title: "Minimum Cost Tree From Leaf Values", difficulty: "Medium", slug: "minimum-cost-tree-from-leaf-values" },
      { id: 1312, title: "Minimum Insertion Steps to Make a String Palindrome", difficulty: "Hard", slug: "minimum-insertion-steps-to-make-a-string-palindrome" },
      { id: 1547, title: "Minimum Cost to Cut a Stick", difficulty: "Hard", slug: "minimum-cost-to-cut-a-stick" }
    ]
  }
];

// Helper array flat list for quick lookup by ID or slug
const FLAT_PROBLEMS_LIST = [];
LEETCODE_DATABASE.forEach(cat => {
  cat.problems.forEach(p => {
    FLAT_PROBLEMS_LIST.push({
      ...p,
      categoryName: cat.category,
      categoryPatterns: cat.patterns
    });
  });
});
